export const GET_INTERSECTIONS = "GET_INTERSECTIONS";
export const ADD_INTERSECTION = "ADD_INTERSECTION";
export const DELETE_INTERSECTION = "DELETE_INTERSECTION";
export const UPDATE_INTERSECTION = "UPDATE_INTERSECTION";
